#!/bin/bash

# check all the PCR EasyCrypt scripts

# SMT timeout in seconds -- try increasing

timeout=2

check() {
  echo checking $1;
  if easycrypt -timeout $timeout $1;
  then echo passed: $1;
       echo "";
  else echo failed: $1;
       echo "";
       echo "skipping remaining scripts";
  exit 1;
  fi;
}

echo "********** Checking PCR EasyCrypt Scripts **********"
echo ""

echo "********** Auxiliary Theories **********"
echo ""

check DistrAux.ec
check MapAux.ec
check FSetAux.ec
check ListAux.ec

echo "********** Supporting Theories **********"
echo ""

check Shuffle.eca
check RandomOracle.eca
check SecretGuessing.eca
check SecrecyRandomOracle.eca
check Inj.ec
check NumOccs.ec
check ElemsCounts.ec

echo "********** PCR Protocol **********"
echo ""

check Protocol.ec

echo "********** Security Against Server **********"
echo ""

check Server.ec

echo "********** Security Against TP **********"
echo ""

check TP.ec

echo "********** Security Against Client **********"
echo ""

check Client.ec

# success!

exit 0
